#!/usr/bin/env ruby

def encode (directory)
  Dir.chdir(directory) do
    flacs = Dir.glob("*").select{ |f| File.file?(f) && f.match(/.+\.flac/) }
    if (flacs.length > 0)
      puts "-------------------- #{directory} --------------------"
      system("flac2aac")
    end
  end
end

directories = Dir.glob("*").select{ |f| File.directory?(f) }

directories.each{ |dir| encode(dir) }
